-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 10:48:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema techroom
-- -----------------------------------------------------
-- Tech Room System
DROP SCHEMA IF EXISTS `techroom` ;

-- -----------------------------------------------------
-- Schema techroom
--
-- Tech Room System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techroom` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `techroom` ;

-- -----------------------------------------------------
-- Table `techroom`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techroom`.`status` ;

CREATE TABLE IF NOT EXISTS `techroom`.`status` (
  `idstatus` INT NOT NULL,
  `status` VARCHAR(15) NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `techroom`.`faultcode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techroom`.`faultcode` ;

CREATE TABLE IF NOT EXISTS `techroom`.`faultcode` (
  `idfaultcode` INT UNSIGNED NOT NULL,
  `faultcode` VARCHAR(15) NULL,
  `perhour` INT NULL DEFAULT 0,
  PRIMARY KEY (`idfaultcode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techroom`.`partreplace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techroom`.`partreplace` ;

CREATE TABLE IF NOT EXISTS `techroom`.`partreplace` (
  `idpartreplace` INT UNSIGNED NOT NULL,
  `partreplace` VARCHAR(20) NULL,
  UNIQUE INDEX `idpartreplace_UNIQUE` (`idpartreplace` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techroom`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techroom`.`users` ;

CREATE TABLE IF NOT EXISTS `techroom`.`users` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techroom`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techroom`.`employees` ;

CREATE TABLE IF NOT EXISTS `techroom`.`employees` (
  `idemployee` INT NOT NULL,
  `firstname` VARCHAR(15) NOT NULL,
  `lastname` VARCHAR(15) NULL,
  `idlevel` INT NOT NULL,
  `iddepartment` INT NOT NULL,
  PRIMARY KEY (`idemployee`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
